spring:
  data:
    mongodb:
      authentication-database: admin
      username: baku
      password: baku1
      host: localhost
      port: 27017
      database: barca2
      auto-index-creation: true

server:
  port: 4404
